name: Minify JS/CSS

on:
  push:
    branches:
      - main
      - fe-rewrite

jobs:

  build:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Compile
      run: |
        sudo apt install yui-compressor
        yui-compressor smiggins/static/app.js --type js  --nomunge > smiggins/static/app.js
        yui-compressor smiggins/static/base.css --type css > smiggins/static/base.css

    - name: Commit
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add smiggins/static/app.js
        git add smiggins/static/base.css
        git diff --cached --quiet || (git commit -m 'minify JS/CSS' && git push)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
